### ISSUE TITLE
The kubeconfig file is not created

### ISSUE THREAD

**Issue by bsctl** [clastix/kubectl-login#14]
In some conditions the output `kubeconfig` file is not created. After a successfully login, the `.kubectl-login.yaml` is created but the `kubeconfig` is missing. When this happens, the login process seems to terminate abruptly. 

```
kubectl-login --k8s-api-server=https://REDACTED \
--oidc-server=https://REDACTED \
--oidc-insecure-skip-tls-verify \
--oidc-client-id=REDACTED

Proceed to login to the following link using your browser:

REDACTED

Type the verification code: REDACTED
User input code is REDACTED
```

I noted that this happens always running the command from a remote ssh session in a CentOS 7 machine. It does not happens running the command from a remote ssh session in a Ubuntu machine.

Which debug option should we enable in order to understand the issue?

**Comment by bsctl** [comment]
I built the command from the master branch.

**Comment by prometherion** [comment]
Please, can you enable debug logging using the `-v` flag?

Is the desired path for the `kubeconfig` writable by the user running the command?

**Comment by bsctl** [comment]
@prometherion the issue is no more reproducible but we do not have more the same setup. Closing for now.
