### ISSUE TITLE
Automatically export KUBECONFIG enviroment

### ISSUE THREAD

**Issue by gdurifw** [clastix/kubectl-login#16]
Describe the feature

Hi all.
I would like a lot a feature that automatically export the KUBECONFIG for the user after complete the login process

What would the new user story look like?

Once a user has completed the login process, kubetcl-login automatically export the KUBECONFIG for the user, instead of ask to the user to export with the command "export KUBECONFIG=oidc.kubeconfig"

**Comment by prometherion** [comment]
I can take care of this, however, keep in mind that the exported `KUBECONFIG` environment variable would be set just for the current session: is it ok or do you prefer overwriting (or rather, merging) the new Kubeconfig configuration with the default one (`~/.kube/config`)?

**Comment by prometherion** [comment]
> keep in mind that the exported KUBECONFIG environment variable would be set just for the current session

No, this is incorrect. Exported environment variable are living just in the running process, so doing `os.Setenv("kubeconfig", path)` would work just for the `kubectl-login` process.

What we could do is to avoid asking for a mandatory `--kubeconfig-path`, performing merging in case of a previous configuration, or a new one in case it doesn't exist.

WDYT @gdurifw?

**Comment by gdurifw** [comment]
So, optionally the user can pass the parameter --kubeconfig-path with the path of the kubeconfig, and if it already exists, merge it.

I think it would be perfect :)
