### ISSUE TITLE
Kubectl-login error in case of wrong --oidc-server parameter

### ISSUE THREAD

**Issue by gdurifw** [clastix/kubectl-login#9]
Hi ! 
I Just found this little problem with parameter --oidc-server .

If I submit the parameter --oidc-server with a url of a non-existent IDP 

`
ES: --oidc-server=https://"Wrong Url Oidc Server"/auth/realms/domain/
`

Or in the case of IDP Keycloack  I submit the parameter --oidc-server  without specifying the complete url path to the oidc domain:

`
ES: --oidc-server=https://"Right Url Oidc Server"
`

Obtain the error below and kubectl-login exit :

`
2021-01-29T12:06:51.567+0100    INFO    cmd/root.go:105 Starting the login procedure
2021-01-29T12:06:51.568+0100    INFO    actions/oidc_config.go:63       Starting OIDC login with PKCE
2021-01-29T12:06:51.568+0100    INFO    actions/oidc_config.go:74       Getting OIDC configuration from the server      {"OIDCServer": "https://XXX.XXX.XXX.XXXX"}
2021-01-29T12:06:51.613+0100    ERROR   actions/oidc_config.go:87       Cannot unmarshal OIDC configuration     {"OIDCServer": "https://XXX.XXX.XXX.XXXX", "error": "invalid character '<' looking for beginning of value"}
github.com/clastix/kubectl-login/internal/actions.PKCELogin.GetOpenIDConfig
        /home/runner/work/kubectl-login/kubectl-login/internal/actions/oidc_config.go:87
github.com/clastix/kubectl-login/internal/actions.PKCELogin.Handle
        /home/runner/work/kubectl-login/kubectl-login/internal/actions/oidc_config.go:65
github.com/clastix/kubectl-login/cmd.glob..func3
        /home/runner/work/kubectl-login/kubectl-login/cmd/root.go:116
github.com/spf13/cobra.(*Command).execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/clastix/kubectl-login/cmd.Execute
        /home/runner/work/kubectl-login/kubectl-login/cmd/root.go:237
main.main
        /home/runner/work/kubectl-login/kubectl-login/main.go:21
runtime.main
        /opt/hostedtoolcache/go/1.14.14/x64/src/runtime/proc.go:203
Error: invalid character '<' looking for beginning of value
invalid character '<' looking for beginning of value

`

**Comment by prometherion** [comment]
Thanks for reporting this!

Not entirely a bug but we can improve the error handling, thanks!
